"""Actualizar estructura

Revision ID: 69f8f90b3977
Revises: 5e7f3f3c9879
Create Date: 2021-12-13 20:42:38.124777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f8f90b3977'
down_revision = '5e7f3f3c9879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
